// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqAlp56gg76hV6kwtK9EDwJraZtkIeb6E',
    appId: '1:459891886520:web:2c9b105eacc7bc510d274d',
    messagingSenderId: '459891886520',
    projectId: 'flutterfirebase-27ce8',
    authDomain: 'flutterfirebase-27ce8.firebaseapp.com',
    storageBucket: 'flutterfirebase-27ce8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaYJEm1LbVloDEbt-OMJnMyH5AnI-rVcE',
    appId: '1:459891886520:android:c6d30cd4e7fd7d050d274d',
    messagingSenderId: '459891886520',
    projectId: 'flutterfirebase-27ce8',
    storageBucket: 'flutterfirebase-27ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4nfD6FOtBtkz-bBz5ok9d8Qufa77sE3w',
    appId: '1:459891886520:ios:4c8904242a83dcea0d274d',
    messagingSenderId: '459891886520',
    projectId: 'flutterfirebase-27ce8',
    storageBucket: 'flutterfirebase-27ce8.appspot.com',
    iosClientId: '459891886520-ufsqj1q93t4qgks1qp9785p99qq0v01q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4nfD6FOtBtkz-bBz5ok9d8Qufa77sE3w',
    appId: '1:459891886520:ios:4c8904242a83dcea0d274d',
    messagingSenderId: '459891886520',
    projectId: 'flutterfirebase-27ce8',
    storageBucket: 'flutterfirebase-27ce8.appspot.com',
    iosClientId: '459891886520-ufsqj1q93t4qgks1qp9785p99qq0v01q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPractice',
  );
}
